apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: result
  name: result
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 80
    - name: "9229"
      port: 9229
      targetPort: 9229
  selector:
    io.kompose.service: result
