apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: result
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: result
    spec:
      containers:
        - command:
            - nodemon
            - --inspect=0.0.0.0
            - server.js
          image: result
          name: result
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 9229
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/local/app
              name: result-claim0
      restartPolicy: Always
      volumes:
        - name: result-claim0
          persistentVolumeClaim:
            claimName: result-claim0
