apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vote
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: vote
    spec:
      containers:
        - image: dockersamples/examplevotingapp_vote
          name: vote
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/local/app
              name: vote-claim0
      restartPolicy: Always
      volumes:
        - name: vote-claim0
          persistentVolumeClaim:
            claimName: vote-claim0
